version: "3.8"

services:
   sentiment-analyzer:
      build:
         context: .
         dockerfile: Dockerfile
      image: sentiment-analysis:latest
      container_name: sentiment-analyzer
      volumes:
         - ./data:/app/data
         - ./models:/app/models
      ports:
         - "8080:8080"
      command: ["--interactive"]
      restart: unless-stopped
      environment:
         - SENTIMENT_LOG_LEVEL=info
      tty: true
      stdin_open: true

   # Example of how to run the API example
   api-example:
      build:
         context: .
         dockerfile: Dockerfile
      image: sentiment-analysis:latest
      container_name: sentiment-api-example
      volumes:
         - ./data:/app/data
         - ./models:/app/models
      command: ["/app/api_example", "/app/data/sample_data.csv"]
      restart: "no"
      depends_on:
         - sentiment-analyzer
